In [1]:
from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
tokens = tokenizer.tokenize("This is an example of the bert tokenizer")
print(tokens)
# ['this', 'is', 'an', 'example', 'of', 'the', 'bert', 'token', '##izer']


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

/usr/local/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

['this', 'is', 'an', 'example', 'of', 'the', 'bert', 'token', '##izer']


In [2]:

token_ids = tokenizer.convert_tokens_to_ids(tokens)
print(token_ids)
# [2023, 2003, 2019, 2742, 1997, 1996, 14324, 19204, 17629]


[2023, 2003, 2019, 2742, 1997, 1996, 14324, 19204, 17629]


In [3]:

token_ids = tokenizer.encode("This is an example of the bert tokenizer")
print(token_ids)
# [101, 2023, 2003, 2019, 2742, 1997, 1996, 14324, 19204, 17629, 102]


[101, 2023, 2003, 2019, 2742, 1997, 1996, 14324, 19204, 17629, 102]


In [4]:

tokens = tokenizer.convert_ids_to_tokens(token_ids)
print(tokens)
# ['[CLS]', 'this', 'is', 'an', 'example', 'of', 'the', 'bert', 'token', '##izer', '[SEP]']


['[CLS]', 'this', 'is', 'an', 'example', 'of', 'the', 'bert', 'token', '##izer', '[SEP]']


In [5]:

import torch
from transformers import BertModel

model = BertModel.from_pretrained("bert-base-uncased")

# get the embedding vector for the word "example"
example_token_id = tokenizer.convert_tokens_to_ids(["example"])[0]
example_embedding = model.embeddings.word_embeddings(torch.tensor([example_token_id]))

print(example_embedding.shape)
# torch.Size([1, 768])

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

torch.Size([1, 768])


Original float32 tensor:
tensor([[-1.2445, -1.0739, -0.1323, -0.6470],
        [-0.8300, -1.3338,  1.4549, -0.2420]])
Shape: torch.Size([2, 4])

Converted to float64 tensor:
tensor([[-1.2431e-02, -1.6498e-04],
        [-5.2191e-02, -8.8639e-08]], dtype=torch.float64)
Shape: torch.Size([2, 2])

Converted back to float32 tensor:
tensor([[-1.2445, -1.0739, -0.1323, -0.6470],
        [-0.8300, -1.3338,  1.4549, -0.2420]])
Shape: torch.Size([2, 4])
